### ISSUE TITLE
Support for data of different length in StackedAreaChart?

### ISSUE THREAD

**Issue by Amnesthesia** [JesperLekland/react-native-svg-charts#46]
### What is the problem?
StackedAreaChart accepts an array of objects, in which all datapoints are specified by keys. I have a use-case where I have two separate "timelines", where I want to show data from two data-sets that dont necessarily have the same length.

For example, I have one chart with data points + timestamps, and I want to display this along with another set of datapoints with different timestamps. 

One solution would be to inject the second set into the first one based on the "closest" timestamp for each value, but this doesn't seem like a good solution.

Could StackedAreaChart support datasets of different length?

Lets say I want to show amount of page visits for a page, in correlation with how many times a topic is mentioned on Twitter:

```javascript
// Page visits per hour
const pageVisits = [
  { visits: 149, timestamp: 1518388122 },
  { visits: 123, timestamp: 1518391722 },
  { visits: 180, timestamp: 1518395322 },
  { visits: 190, timestamp: 1518398922 },
  { visits: 430, timestamp: 1518402502 },
  { visits: 614, timestamp: 1518406522 },
  { visits: 590, timestamp: 1518409722 },
  { visits: 301, timestamp: 1518413322 },
  { visits: 159, timestamp: 1518416922 },
  { visits: 140, timestamp: 1518420522 },
]

// Mentions for a topic on Twitter
const mentions = [
  { mentions: 3, timestamp: 1518389240 },
  { mentions: 2, timestamp: 1518394852 },
  { mentions: 3, timestamp: 1518398495 },
  { mentions: 45, timestamp: 1518402853 },
  { mentions: 87, timestamp: 1518405495 },
  { mentions: 120, timestamp: 1518408928 },
  { mentions: 90, timestamp: 15184135032 }
]
```

Would it be possible to show two charts with different datapoints but along the same "timeline" on top of each other?

### What platform?

* [X] iOS 
* [X] Android

**Comment by JesperLekland** [comment]
I'm not a 100% sure I understand your problem. Do you have a visualisation I can work off of?

**Comment by Amnesthesia** [comment]
So, the problem is that StackedAreaChart expects an array of objects with all dataPoints, but I have two lists of different objects. Both objects have a timestamp used for the x-axis, but they have different values at different keys for the y-axis.

If I merged those two lists (as in the example above), then some objects would have the "visits" key and others would have the "mentions" key, but I want to graph these together

**Comment by Amnesthesia** [comment]
Essentially I want to plot two different data sets with two different Y-axises but with the same x-axis 

I'll see if I can come up with a better example

**Comment by JesperLekland** [comment]
Still not quite sure I get the use case 😝 sorry. Try finding an existing chart that displays the behaviour. Explaining data visualisation is always tricky

**Comment by Amnesthesia** [comment]
Alright - here's an example: https://www.highcharts.com/demo/spline-irregular-time

I have different datasets, that need to be charted along a timeline, but the timestamps are different in the different datasets

**Comment by JesperLekland** [comment]
In that example they don't use a stacked chart and the datasets don't depend on each other. Maybe you should use a [layered chart](https://github.com/JesperLekland/react-native-svg-charts#layered-charts)?

**Comment by Amnesthesia** [comment]
Holy shit, you reply fast.

That does look like the way to go — I should've seen that sooner. Thank you so much! Oh, and thank you *so* much for this library. I was rolling my own when, 2 weeks later, this pops up out of nowhere and abstracts all the SVG path painting away. Thank you!

**Comment by JesperLekland** [comment]
Haha, glad I can help 😄 Don't forget to give it a star if you haven't already. 
And if you want to contribute just create a PR and I will happily look at it 😊

**Comment by Amnesthesia** [comment]
The one thing that *is* still an issue, though, is that although the datapoints dont technically "depend" on each other, they do depend on the timestamp and should be aligned according to their timestamp (e.g, if there are fewer values in one of the layered charts, but the timestamp is earlier than the last one  in the other datasets), so in a way, I suppose the X-axis points do depend on eachother, in that the "timeline" still has to align well

**Comment by JesperLekland** [comment]
You could just modify your dataset to have the same "x-values" and just have `undefined` as values where it's suitable (they won't be rendered). I'll keep this in mind as I go forward though, maybe have something similar to `gridMin/Max` but for the x-axis

**Comment by Amnesthesia** [comment]
That could be a possibility, definitely - perhaps having something like a Time chart would make sense as well, for cases where you want to plot lines along a time axis but where the different lines' dataPoints are independent of each other, but dependent on the timeline

**Comment by JesperLekland** [comment]
A time scale for the xAxis is already included in the 3.0 release (planned release this week). But aligning two (or more) datasets still requires them to share the same x-axis domain (min/max)

**Comment by Amnesthesia** [comment]
For my usecase, they already do share the same domain (e.g displaying data for a month, or the past year, etc) but each dataset has different points (e.g when displaying data for January 2018, one line may have points for the 3rd, 5th and 20th and another line may have points for the 5th, 6th and 18th). 

That's awesome though! Looking forward for 3.0 — excited about partial charts as well! :-)

**Comment by JesperLekland** [comment]
Well that shouldn't be a problem at all, should work out of the box. If it doesn't could you please supply a screenshot? 

Partial Charts and the new `extras` api is awesome 💪

**Comment by Amnesthesia** [comment]
Sure thing, as soon as it's released I'll give feedback on it — my app is heavy on these kinds of charts and I've found no good way to do it yet, so I'll be happy to test it out!

**Comment by JesperLekland** [comment]
You should be able to do what you've described on the existing release though. Have you tried it?
