### ISSUE TITLE
Error while updating property 'd' in shadow node

### ISSUE THREAD

**Issue by dineshmm23** [JesperLekland/react-native-svg-charts#81]
### What is the problem?
Unable to set the value of barchart to 0 which causes me to give below error.

![screenshot_2018-03-07-20-12-30 1](https://user-images.githubusercontent.com/22963956/37098690-8696510a-2244-11e8-8f34-6720103211a0.png)  

### When does it happen?
```
import React from 'react'
import { BarChart } from 'react-native-svg-charts'
import { Defs, LinearGradient, Stop } from "react-native-svg";

class ColorBarExample extends React.PureComponent {

    render() {

        const barDataCritical = [
      {
        value:0,
      },
      {
        value: 0, **// ERROR HAPPPENS WHEN I SET VALUE TO 0**
        svg: {
          fill: 'rgb(226, 225, 223)',
        },
      },
      {
        value: 3,
        svg: {
          fill: 'rgb(239, 203, 133)',
        },
      },
    ];

        return (
            <BarChart
                style={{ height: 200 }}
                data={barDataCritical}
                gridMin={0}
                svg={{ fill: 'rgba(134, 65, 244, 0.8)' }}
                yAccessor={({ item }) => item.value}
                contentInset={{ top: 20, bottom: 20 }}
            />
        )
    }

}

export default ColorBarExample
```

I'm using these [Barchart](https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/bar-chart/with-different-bars.js)

### What platform?   

> "react": "16.1.0",
>     "react-native": "0.54.0",
>     "react-native-svg": "^6.2.2",
>     "react-native-svg-charts": "^4.0.0",
>     "react-native-vector-icons": "^4.5.0"

**Comment by JesperLekland** [comment]
Are you using the `yAccessor` prop? Please provide a full example for us to be able to help

**Comment by dineshmm23** [comment]
<BarChart
                    style={{ height: 200, width: 200 }}
                    data={barDataProduction}
                    showGrid={false}
                    svg={{ fill: 'rgb(167, 212, 251)' }}
                    yAccessor={({ item }) => item.value}
                    contentInset={{ top: 20, bottom: 20 }}
                  />

**Comment by dineshmm23** [comment]
yes i have used it .. but even when if reinstall the `node_modules` it gives same error..

**Comment by JesperLekland** [comment]
I'll have a look and get back to you :)

**Comment by JesperLekland** [comment]
It was indeed a bug, fixed in 4.0.1 👍

**Comment by nomikeeper** [comment]
It this error somewhat related to this? 
![screen shot 2018-07-23 at 16 52 58](https://user-images.githubusercontent.com/10585040/43064104-f4447c84-8e98-11e8-8012-704e109e75f4.png)

I've been trying to figure out what is this error. On IOS there was no problem but on Android it's giving me this error. In case if you are wondering what would my source code looks like:

 ```
           <View style={{ height: 200, padding: 20, flexDirection: 'row' }}>
                <YAxis
                    data={ data }
                    yAccessor={ ({ item }) => item.value }
                    style={{ marginBottom: xAxisHeight, flex:1}}
                    contentInset={verticalContentInset}
                    svg={axesSvg}
                />
                <View style={{flex:15,}}>
                    <AreaChart
                        style={{flex:1, borderWidth:1, borderColor:"#aaa" }}
                        data={ data }
                        yAccessor={ ({ item }) => item.value }
                        xAccessor={ ({ item }) => moment(item.date).format("YYYY-MM-DD HH:mm")}
                        formatLabel={() => { 
                            return data.map((item) => { return moment(item.date).format("HH/mm") })
                        }}
                        contentInset={{ top: 10, bottom: 10 }}
                        svg={{ fill: "rgba(26,179,148,0.5)" }}
                        showGrid={true}
                    >
                        {
                            console.log(data)
                        }
                        <Grid direction={"BOTH"}/>
                        <Line />
                    </AreaChart> 
                    <XAxis
                        style={{marginHorizontal: -10, height: xAxisHeight}}
                        data={data}
                        xAccessor={ ({ item }) => { moment(item.date).format("HH:mm") }}
                        
                        formatLabel={() => { 
                            return data.map((item) => { return moment(item.date).format("HH/mm") })
                        }}
                        contentInset={{ left: 20, right: 10 }}
                        svg={axesSvg}
                    />
                </View>
            </View>
```

**Comment by JesperLekland** [comment]
I'm pretty sure the AreaChart can't take a formatted date string as the xAccessor value. 
You probably need 
```jsx
xAccessor={ ({ item })  => item.date}
xScale= { scale.dateTime }
```

**Comment by nomikeeper** [comment]
I changed the AreaChart into this but I'm still getting the same error. 
```
                    <AreaChart
                        style={{flex:1, borderWidth:1, borderColor:"#aaa" }}
                        data={ data }
                        yAccessor={ ({ item }) => item.value }
                        xAccessor={ ({ item }) => item.date}
                        xScale= { scale.dateTime }
                        formatLabel={() => { 
                            return data.map((item) => { return moment(item.date).format('HH/mm') })
                        }}
                        contentInset={{ top: 10, bottom: 10 }}
                        svg={{ fill: 'rgba(26,179,148,0.5)' }}
                        showGrid={true}
                        >
                        <Grid direction={'BOTH'}/>
                        <Line />
                    </AreaChart> 
```

Btw, the data I'm providing is just a constant array.
```

 const data = [
            {
                value: 500,
                date: "2018-07-19T16:30"
            },
            {
                value: 450,
                date: "2018-07-20T18:30"
            },
            {
                value: 650,
                date: "2018-07-20T20:30"
            },
            {
                value: 1000,
                date: "2018-07-21T18:30"
            },
            {
                value: 250,
                date: "2018-07-21T20:30"
            },
            {
                value: 450,
                date: "2018-07-22T18:30"
            },
        ]
```

**Comment by nomikeeper** [comment]
When I changed:

                        `xAccessor={ ({ item }) => item.date}`
to

                        `xAccessor={({index}) => index}`

the chart is working fine.

**Comment by JesperLekland** [comment]
Ah you're using date strings not date objects, in that cause you should probably do `xAccessor={ ({item}) => new Date(item.date) }`
